module.exports = {
  apps: [
    {
      name: 'finance-seer-heartbeat',
      script: 'node',
      args: './heartbeat.js',
      cwd: '/home/joobi/.openclaw/workspace/finance-seer/scripts',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORTAL_URL: 'https://finance-seer.vercel.app',
        TELEGRAM_BOT_TOKEN: '8609316971:AAFhvA7fOyXRx5ch5Mm740ajcjMRD5brIr4',
        TELEGRAM_CHAT_ID: '786437034',
      },
      error_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/heartbeat-error.log',
      out_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/heartbeat.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
    },
    {
      name: 'finance-seer-monitor',
      script: 'python3',
      args: './monitor.py',
      cwd: '/home/joobi/.openclaw/workspace/finance-seer/scripts',
      env: {
        NODE_ENV: 'production',
        PORTAL_URL: 'https://finance-seer.vercel.app',
        TELEGRAM_BOT_TOKEN: '8609316971:AAFhvA7fOyXRx5ch5Mm740ajcjMRD5brIr4',
        TELEGRAM_CHAT_ID: '786437034',
        PYTHONUNBUFFERED: '1',
      },
      error_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/monitor-error.log',
      out_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/monitor.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
      watch: false,
    },
    {
      name: 'finance-seer-health-monitor',
      script: 'node',
      args: './health-monitor.js',
      cwd: '/home/joobi/.openclaw/workspace/finance-seer/scripts',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORTAL_URL: 'https://finance-seer.vercel.app',
      },
      error_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/health-monitor-error.log',
      out_file: '/home/joobi/.openclaw/workspace/finance-seer/logs/health-monitor.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      time: true,
      max_memory_restart: '500M',
    }
  ],
};
